### ISSUE TITLE
Unreadable colors for source code snippets

### ISSUE THREAD

**Issue by habernal** [graphstream/graphstream.github.io#1]
`<figure class="highlight"><pre><code class="language-java" data-lang="java">`

displays some text in yellow, which is unreadable (see attached screenshot)

![screenshot-graphstream-doc](https://cloud.githubusercontent.com/assets/11850778/13285467/089c8b12-dafb-11e5-852e-84665d8be379.png)

**Comment by gsavin** [comment]
Fixed.
